//
// Created by WhiteBlue on 2020/7/22.
//

#ifndef NEOSYCL_INCLUDE_CL_SYCL_DETAIL_PROFILER_H_
#define NEOSYCL_INCLUDE_CL_SYCL_DETAIL_PROFILER_H_

#endif //NEOSYCL_INCLUDE_CL_SYCL_DETAIL_PROFILER_H_
