#ifndef NEOSYCL_INCLUDE_NEOSYCL_SYCL_DETAIL_DEVICE_TYPE_HPP
#define NEOSYCL_INCLUDE_NEOSYCL_SYCL_DETAIL_DEVICE_TYPE_HPP

namespace neosycl::sycl::detail {

enum SUPPORT_PLATFORM_TYPE : int { CPU, VE };

}

#endif // NEOSYCL_INCLUDE_NEOSYCL_SYCL_DETAIL_DEVICE_TYPE_HPP
