#ifndef NEOSYCL_INCLUDE_NEOSYCL_SYCL_DETAIL_TASK_HPP
#define NEOSYCL_INCLUDE_NEOSYCL_SYCL_DETAIL_TASK_HPP

namespace neosycl::sycl::detail {



}

#endif //NEOSYCL_INCLUDE_NEOSYCL_SYCL_DETAIL_TASK_HPP
